import './form_elements.pug'
import './form_elements.less'

import '../../components/blocks/ui-logo/ui-logo.js'
import '../../components/blocks/input-block/input-block.js'
import '../../components/blocks/checkbox-block/checkbox-block.js'
import '../../components/blocks/radio-block-list/radio-block-list.js'
import '../../components/blocks/toggle-block/toggle-block.js'
import '../../components/blocks/like-block/like-block.js'
import '../../components/blocks/rate-block/rate-block.js'
